name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install packages
      run: |
        sudo apt update
        sudo apt install -y xfonts-utils bdf2psf

        mkdir -p $PWD/ci-dist
        mkdir -p $PWD/ci-install
        mkdir -p genpcf
        mkdir -p genotbbdf
        mkdir -p genotb
    
    - run: ls -la
    - run: ./configure --help
    - run: ./configure --installdirs=$PWD/ci-dist --prefix=$PWD/ci-install
    - run: make
    - run: make otb
    - run: make conslinux
    - run: make install
    - run: ls -la
    - uses: actions/upload-artifact@v4
      with:
        path: .
